# Data Science Project | Common Vulnerability Exposures 
# Phase 3 - Data Manipulation 

### During this phase we created 4 functions that mainpulate the data:

1. **function load_dataframe** - will load our csv file into a dataframe.
2. **function remove_unnecessary_data** - will remove a column that contain only None value, will remove rows with the CVE Score of 0, the removal is necessary since that CVE Score 0 indicates that the row is not actually a vulnerability, but more of a informational view of a product, will remove the vulnerabilities that is not in the last decade, since our project is  concerned with the last decade only, will remove duplicate rows and will keep the first one.
3. **function replace_missing_data** - will replace missing values such as '???' and NaN with the 0 value, we kept the rows with null values on our dataframe since a row could have a null values on a feature of a vulnerability but the key value of a vulnerability such as the CVE score was not null.
4. **function convert_string_to_int** - will convert each string value to an int value based on the diffrent columns, this function is mostly necessary for the machine learning phase. the values were converted mostly based on unique values and specific date was converted to a year since the month and day was not important for our research question

In [74]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [75]:
def load_dataframe(filename):
    return pd.read_csv(filename)

df = load_dataframe('cve_DF.csv')

In [76]:
#Printing the dataframe befor manipulation
print("The dataframe befor manipulation:")
df.head(3000)

The dataframe befor manipulation:

,CVE_ID,Vulnerability Type,Publish Date,Update Date,Score,Gained Access Level,Access,Complexity,Authentication,Confidentiality,Integrity,Availability
0,CVE-2022-29603,\n\t\t\t\t\t\tSql \t\t\t\t\t,25/04/2022,25/04/2022,0.0,None,???,???,???,???,???,???
1,CVE-2022-29589,\n\t\t\t\t\t\tXSS \t\t\t\t\t,22/04/2022,22/04/2022,0.0,None,???,???,???,???,???,???
2,CVE-2022-29583,\n,22/04/2022,22/04/2022,0.0,None,???,???,???,???,???,???
3,CVE-2022-29582,\n,22/04/2022,22/04/2022,0.0,None,???,???,???,???,???,???
4,CVE-2022-29577,\n\t\t\t\t\t\tXSS \t\t\t\t\t,21/04/2022,22/04/2022,0.0,None,???,???,???,???,???,???
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CVE-2021-20295,\n,01/04/2022,08/04/2022,2.1,None,Local,Low,Not required,Partial,None,None
2996,CVE-2021-20269,\n\t\t\t\t\t\t+Info \t\t\t\t\t,10/03/2022,15/03/2022,2.1,None,Local,Low,Not required,Partial,None,None
2997,CVE-2021-20263,\n,09/03/2021,01/01/2022,2.1,None,Local,Low,Not required,None,Partial,None
2998,CVE-2021-20257,\n\t\t\t\t\t\tDoS \t\t\t\t\t,16/03/2022,25/04/2022,2.1,None,Local,Low,Not required,None,None,Partial
2999,CVE-2021-20255,\n\t\t\t\t\t\tDoS Overflow \t\t\t\t\t,09/03/2021,11/04/2021,2.1,None,Local,Low,Not required,None,None,Partial

In [77]:
#Exploring the data befor manipulation
print("shape of the dataframe:" ,df.shape)
print("\nThe dataframe count of null values:\n",df.isnull().sum(axis = 0))
df.describe(include='all')

shape of the dataframe: (174953, 12)

The dataframe count of null values:
 CVE_ID                 0
Vulnerability Type     0
Publish Date           0
Update Date            0
Score                  0
Gained Access Level    0
Access                 0
Complexity             0
Authentication         0
Confidentiality        0
Integrity              0
Availability           0
dtype: int64

,CVE_ID,Vulnerability Type,Publish Date,Update Date,Score,Gained Access Level,Access,Complexity,Authentication,Confidentiality,Integrity,Availability
count,174953,174953,174953,174953,174953.000000,174953,174953,174953,174953,174953,174953,174953
unique,174943,214,6463,3511,NaN,1,4,4,3,4,4,4
top,CVE-2022-29603,\n,31/12/2004,03/10/2019,NaN,None,Remote,Low,Not required,Partial,Partial,Partial
freq,2,50220,1098,5740,NaN,174953,144671,101722,147459,85881,92051,74851
mean,NaN,NaN,NaN,NaN,5.884570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,2.018607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
def remove_unnecessary_data(dataframe):
    
    df = dataframe.copy()
    
    #remove a column that contain only None
    df.drop('Gained Access Level', inplace=True, axis=1)
    
    #remove all the rows with vulnerability score 0
    df = df[df.Score != 0.0]
    
    #remove all the vulnerabilities from over a decade
    for i in range(1998,2012):
        df = df[df["CVE_ID"].str.contains(str(i)) == False]
    
    #remove duplicate rows
    df = df.drop_duplicates(keep='first').copy() 
    
    return df

In [79]:
def replace_missing_data(dataframe):
    # Fill null values with 0
    dt = dataframe.copy()
    dt['Authentication'].mask(dt['Authentication'] == '???', 0, inplace=True)
    dt = dt.fillna(0)
    
    return dt

In [80]:
def convert_string_to_int(dataframe):
    
    df = dataframe.copy()
        
    # Convert CVE_ID from string to int
    df['CVE_ID'] = df['CVE_ID'].str.replace("-","")
    df['CVE_ID'] = df['CVE_ID'].str.replace("CVE","")
    
    # Convert Vulnerability Type to unique values
    df.rename(columns = {'Vulnerability Type': 'VulnerabilityType'}, inplace=True)
    le = LabelEncoder()
    df['VulnerabilityType'] = le.fit_transform(df.VulnerabilityType)
    
    # Convert date to datetime 
    df['Publish Date'] = pd.to_datetime(df['Publish Date'])
    df['Update Date'] = pd.to_datetime(df['Update Date'])
    
    # Extract a year from the date time
    df['Update Date'] = pd.DatetimeIndex(df['Update Date']).year
    df['Publish Date'] = pd.DatetimeIndex(df['Publish Date']).year
    
    # Convert Access
    replaceAccess = {'Local':1, 'Local Network':2, 'Remote':3}
    df.replace(replaceAccess,inplace=True)
    
    # Convert Complexity
    replaceComplexity = {'Low':1, 'Medium':2, 'High':3}
    df.replace(replaceComplexity,inplace=True)
    
    # Convert Authentication
    replaceAuthentication = {'Not required':1, 'Single system':2}
    df.replace(replaceAuthentication,inplace=True)
    
    # Convert Confidentiality
    replaceConfidentiality = {'None':1, 'Partial':2, 'Complete':3}
    df.replace(replaceConfidentiality,inplace=True)
    
    # Convert Integrity
    replaceIntegrity = {'None':1, 'Partial':2, 'Complete':3}
    df.replace(replaceIntegrity,inplace=True)
    
    # Convert Availability
    replaceAvailability = {'None':1, 'Partial':2, 'Complete':3}
    df.replace(replaceAvailability,inplace=True)

    return df

In [81]:
df = load_dataframe('cve_DF.csv')
df = remove_unnecessary_data(df)
dt = replace_missing_data(df)
ds = convert_string_to_int(dt)
print("The dataframe after manipulation:")
ds.head(3000)

The dataframe after manipulation:

,CVE_ID,VulnerabilityType,Publish Date,Update Date,Score,Access,Complexity,Authentication,Confidentiality,Integrity,Availability
792,202227841,0,2022,2022,1.9,1,2,1,2,1,1
793,202227049,0,2022,2022,1.9,1,2,1,1,2,1
794,202226355,0,2022,2022,1.9,1,2,1,2,1,1
795,202225831,0,2022,2022,1.9,1,2,1,2,1,1
796,202225368,0,2022,2022,1.9,1,2,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...
4136,20203580,133,2020,2020,2.6,3,3,1,1,2,1
4137,20203541,0,2020,2020,2.1,1,1,1,2,1,1
4138,20203520,1,2020,2020,2.1,1,1,1,2,1,1
4139,20203504,36,2020,2020,2.1,1,1,1,1,1,2
4140,20203477,90,2020,2021,2.1,1,1,1,2,1,1

In [82]:
#Exploring the data after manipulation
print("shape of the dataframe:" ,df.shape)
print("\nThe dataframe count of null values:\n",df.isnull().sum(axis = 0))
df.describe(include='all')

shape of the dataframe: (123144, 11)

The dataframe count of null values:
 CVE_ID                0
Vulnerability Type    0
Publish Date          0
Update Date           0
Score                 0
Access                0
Complexity            0
Authentication        0
Confidentiality       0
Integrity             0
Availability          0
dtype: int64

,CVE_ID,Vulnerability Type,Publish Date,Update Date,Score,Access,Complexity,Authentication,Confidentiality,Integrity,Availability
count,123144,123144,123144,123144,123144.000000,123144,123144,123144,123144,123144,123144
unique,123144,182,3287,2768,NaN,3,3,3,3,3,3
top,CVE-2022-27841,\n,15/04/2020,03/10/2019,NaN,Remote,Low,Not required,Partial,Partial,Partial
freq,1,40409,508,5710,NaN,100732,68571,99199,60943,64146,50955
mean,NaN,NaN,NaN,NaN,5.741184,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,1.954354,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,7.200000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN